config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :cars, only: [:index, :show], defaults: { format: :html }, path: "coches"
  # get "admin22", to: "admin#index"
  devise_scope :user do
    get "/admin22", to: "users/sessions#new"
  end

  get "admin", to: "admin#index"
  get "about_us", to: "static_pages#about_us"
  get "contacto", to: "contact_requests#new", as: "contact_request"
  post "contacto", to: "contact_requests#create"
  get "cookies_policy", to: "static_pages#cookies_policy"
  get "legal", to: "static_pages#legal"
  root "static_pages#home"

  namespace :admin do
    resources :cars do
      member do
        delete "remove_image/:image_id", to: "cars#remove_image", as: "remove_image"
      end
    end

    resources :contact_requests, only: [:index, :update, :destroy]
    resources :categories
    resources :category_types
  end

  # Default routes
  # To know the status of the app /up
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  belongs_to :car, optional: true
end

app/controllers/admin/contact_requests_controller.rb
module Admin
  class ContactRequestsController < AdminController
    def index
      @contact_requests = ContactRequest.all.order(created_at: :desc)
    end

    def update
      contact_request = ContactRequest.find(params[:id])
      if contact_request.update(contact_request_params)
        flash[:success] = "Solicitud actualizada correctamente"
      else
        flash[:error] = "Error al actualizar la solicitud"
      end

      redirect_to admin_contact_requests_path
    end

    def destroy
      contact_request = ContactRequest.find(params[:id])
      if contact_request.destroy
        flash[:success] = "Solicitud eliminada correctamente"
      else
        flash[:error] = "Error al eliminar la solicitud"
      end

      redirect_to admin_contact_requests_path
    end

    private

    def contact_request_params
      params.require(:contact_request).permit(:viewed)
    end
  end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  def new
    @contact_request = ContactRequest.new
    @contact_request.assign_attributes(car_id: params[:car_id]) if params[:car_id].present?
  end

  def create
    @contact_request = ContactRequest.new(contact_request_params)
    if @contact_request.save
      flash[:success] = "Solicitud enviada correctamente, nos pondremos en contacto contigo lo antes posible."
      redirect_to root_path
    else
      flash[:error] = "Error al enviar la solicitud."
      render :new
    end
  end

  private

  def contact_request_params
    params.require(:contact_request).permit(:name, :email, :phone, :subject, :message, :car_id)
  end
end

app/views/contact_requests/new.html.erb
<!-- app/views/contact/new.html.erb -->
<div class="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <h1 class="text-center text-3xl font-bold mb-8">Contáctanos</h1>

  <div class="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-md">
    <%= form_with model: @contact_request, url: contact_request_path, method: :post, local: true, class: "space-y-6" do |f| %>
      <div>
        <%= f.label :name, "Nombre", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= f.text_field :name, class: "w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", required: true %>
        </div>
      </div>
      <div>
        <%= f.label :email, "Correo Electrónico", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= f.email_field :email, class: "w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", required: true %>
        </div>
      </div>
      <div>
        <%= f.label :phone, "Teléfono", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= f.telephone_field :phone, class: "w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
        </div>
      </div>
      <div>
        <%= f.label :subject, "Asunto", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= f.text_field :subject, class: "w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", required: true %>
        </div>
      </div>
      <div>
        <%= f.label :message, "Mensaje", class: "block text-sm font-medium text-gray-700" %>
        <div class="mt-1">
          <%= f.text_area :message, rows: 6, class: "w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm", required: true %>
        </div>
      </div>
      <div class="flex justify-center">
        <%= f.submit "Enviar mensaje", class: "inline-block w-full sm:w-auto bg-indigo-600 text-white text-lg font-medium px-6 py-3 rounded-md hover:bg-indigo-700" %>
      </div>
    <% end %>
  </div>
</div>