config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :cars, only: [:index, :show], defaults: { format: :html }, path: "coches"
  # get "admin22", to: "admin#index"
  devise_scope :user do
    get "/admin22", to: "users/sessions#new"
  end

  get "admin", to: "admin#index"
  get "about_us", to: "static_pages#about_us"
  get "contacto", to: "contact_requests#new", as: "contact_request"
  post "contacto", to: "contact_requests#create"
  get "cookies_policy", to: "static_pages#cookies_policy"
  get "legal", to: "static_pages#legal"
  root "static_pages#home"

  namespace :admin do
    resources :cars do
      member do
        delete "remove_image/:image_id", to: "cars#remove_image", as: "remove_image"
      end
    end

    resources :contact_requests, only: [:index, :update, :destroy]
    resources :categories
    resources :category_types
  end

  # Default routes
  # To know the status of the app /up
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :category
  belongs_to :make
  belongs_to :origin_country, class_name: "Country", foreign_key: "origin_country_id", optional: true

  has_many :contact_requests, dependent: :nullify

  has_many_attached :images

  validates :make, presence: true
  validate :image_count_within_limit
  validates :vin, uniqueness: true, allow_nil: true

  enum :status, { on_sale: 0, sold: 1, reserved: 2 }
  enum :condition, { km0: 0, used: 1 }
  enum :gearbox, { manual: 0, automatic: 1, semi_automatic: 2 }
  enum :transmission, { front_wheel_drive: 0, rear_wheel_drive: 1, four_wheel_drive: 2 }
  enum :fuel, { diesel: 0, petrol: 1, electric: 2, hybrid_petrol: 3, hybrid_diesel: 4, lpg: 5, cng: 6, other: 7 }

  before_save :set_vat_price_fields
  before_save :hide_car_if_sold

  def to_param
    "#{self.name.parameterize}-#{self.id}"
  end

  def image_urls
    self.images.map { |image| Rails.application.routes.url_helpers.url_for(image) }
  end

  def medium_image(image)
    image.variant(resize_to_fill: [300, 200], format: :jpg).processed
    # image.variant(resize_to_limit: [300, 200], format: :jpg).processed
  end

  def mediumbig_image(image)
    image.variant(resize_to_fill: [300, 480], format: :jpg).processed
    # image.variant(resize_to_limit: [300, 480], format: :jpg).processed
  end

  def big_image(image)
    image.variant(resize_to_fill: [1000, 1000], format: :jpg).processed
    # image.variant(resize_to_limit: [1000, 1000], format: :jpg).processed
  end

  def tiny_image(image)
    image.variant(resize_to_fill: [30, 30], format: :jpg).processed
    # image.variant(resize_to_limit: [30, 30], format: :jpg).processed
  end

  def get_full_name
    "#{self.make.name} #{self.name}"
  end

  private

  def image_count_within_limit
    if images.count < 1
      errors.add(:images, "must have at least one image")
    end
  end

  def set_vat_price_fields
    if self.new_record? || self.price_changed?
      tax = self.price * 1.21

      self.tax = tax.round(2)
      self.base_price = (self.price - tax).round(2)
    end
  end

  def hide_car_if_sold
    if self.status == "sold"
      self.in_home_page = false
      self.is_public = false
    end
  end
end

app/controllers/admin/cars_controller.rb
module Admin
  class CarsController < AdminController
    def index
      @cars = Car.all
    end

    def show
      @car = Car.find(get_car_id)
      render template: "cars/show"
    end

    def edit
      all_select_options
      default_form_field_values

      @car = Car.find(get_car_id)
    end

    def new
      all_select_options
      default_form_field_values
    end

    def update
      @car = Car.find(get_car_id)

      if car_params[:images].present?
        @car.images.attach(car_params[:images])
      end

      if @car.update(car_params.except(:images))
        message = "El coche se actualizó correctamente."
        message += " Se ha ocultado de la página de inicio y de la web ya que el coche está vendido." if @car.sold?
        redirect_to admin_car_path(@car), notice: message
      else
        render "edit"
      end
    end

    def create
      @car = Car.new(car_params)
      if @car.save
        flash[:success] = "Coche creado correctamente."
        redirect_to admin_car_path(@car)
      else
        flash[:error] = "Error al crear el coche."
        redirect_to new_admin_car_path(car_params)
      end
    end

    def destroy
      @car = Car.find(get_car_id)
      @car.destroy

      redirect_to admin_cars_path
    end

    def remove_image
      @car = Car.find(get_car_id)
      image = @car.images.find(params[:image_id])
      image.purge  # Elimina la imagen

      redirect_to edit_admin_car_path(@car), notice: "Imagen eliminada con éxito."
    end

    private

    def car_params
      params.require(:car).permit(
        :category_id, :make_id, :emission_sticker_id, :condition, :first_registration, :transmission, :gearbox, :fuel, :model,
        :cubic_capacity, :power, :previous_owners, :origin_country_id,:model_description, :name, :price, :year, :kilometers,
        :description, :in_home_page, :is_public, :status, :next_inspection, :exterior_color, :manufacturer_color_name, :doors, :seats,
        :interior_color, :interior_material, :vin, :consumption_city, :consumption_suburban, :consumption_highway,
        :consumption_combined, :base_price, :tax, :total_price, images: []
      ).tap do |p|
        p[:condition] = p[:condition].to_i if p[:condition].present?
        p[:gearbox] = p[:gearbox].to_i if p[:gearbox].present?
        p[:transmission] = p[:transmission].to_i if p[:transmission].present?
        p[:fuel] = p[:fuel].to_i if p[:fuel].present?
        p[:status] = p[:status].to_i if p[:status].present?
        p[:vin] = p[:vin].presence
      end
    end

    def all_select_options
      @car = Car.new
      @categories = Category.all.order(:name)
      @makes = Make.all.order(:name)
      @emission_stickers = EmissionSticker.all.order(:name)
      @countries = Country.all.order(:name)

      fuels_desired_order = %w[petrol diesel electric hybrid_petrol hybrid_diesel other]
      @fuels = Car.fuels.sort_by { |key, _| fuels_desired_order.index(key.to_s) || fuels_desired_order.size }
      @conditions = Car.conditions.sort_by { |key, _| key.to_s }.reverse.to_h
      @transmissions = Car.transmissions.sort_by { |key, _| key.to_s }.to_h
      @gearboxes = Car.gearboxes.sort_by { |key, _| key.to_s }.to_h
      @statuses = Car.statuses.sort_by { |key, _| key.to_s }.to_h
    end

    def default_form_field_values
      @default_make_id = Make.find_by(name: "Porsche").id
      @default_origin_country_id = Country.find_by(name: "Spain").id
      @default_category_id = Category.find_by(name: "SUV").id
    end
  end
end
# {"on_sale"=>0, "reserved"=>2, "sold"=>1}

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.where.not(status: :sold)
  end

  def show
    @car = Car.find(get_car_id)
  end
end

app/views/admin/cars/_form.html.erb
<% common_input_classes = "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
<% common_label_classes = "block text-gray-700 text-sm font-bold mb-2" %>
<% h3_classes = "text-xl font-bold text-gray-800 mt-12 mb-2" %>
<% common_labels_div_classes =  "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" %>

<%= form_with model: [:admin, @car], local: true, html: { multipart: true } do |form| %>
  <div class="container mx-auto">
    <h1 class="text-3xl font-bold text-gray-800 text-center mt-12 mb-7">Crear o Editar Coche</h1>

    <!-- Información Básica -->
    <h3 class="<%= h3_classes %>">Información Básica</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4">
          <%= form.label :name, "Nombre del Coche", class: common_label_classes %>
          <%= form.text_field :name, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :price, "Precio", class: common_label_classes %>
          <%= form.number_field :price, step: 0.01, required: true, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :status, "Estado venta", class: common_label_classes %>
          <%= form.select :status, @statuses.map { |k, v| [k.humanize, v] }, { selected: @car.status_before_type_cast }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :condition, "Condición", class: common_label_classes %>
          <%= form.select :condition, @conditions.map { |k, v| [k.humanize, v] }, { selected: @car.condition_before_type_cast }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :make_id, "Marca", class: common_label_classes %>
          <%= form.collection_select :make_id, @makes, :id, :name, { selected: @car.make_id || @default_make_id }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :model, "Modelo", class: common_label_classes %>
          <%= form.text_field :model, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :kilometers, "Kilómetros", class: common_label_classes %>
          <%= form.number_field :kilometers, required: true, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :year, "Año", class: common_label_classes %>
          <%= form.select :year, options_for_select((1910..2024).to_a.reverse, @car.year) %>
        </div>
      </div>
    </div>

    <!-- Descripción -->
    <h3 class="<%= h3_classes %>">Descripción</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4 col-span-2">
          <%= form.label :model_description, "Descripción del Coche", class: common_label_classes %>
          <%= form.text_area :model_description, rows: 5, class: common_input_classes %>
        </div>
      </div>
    </div>

    <!-- Información Adicional -->
    <h3 class="<%= h3_classes %>">Información Adicional</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4">
          <%= form.label :previous_owners, "Número de Dueños Previos", class: common_label_classes %>
          <%= form.number_field :previous_owners, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :next_inspection, "Próxima revisión", class: common_label_classes %>
          <%= form.date_field :next_inspection, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :first_registration, "Primera Matriculación", class: common_label_classes %>
          <%= form.date_field :first_registration, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :fuel, "Tipo de Combustible", class: common_label_classes %>
          <%= form.select :fuel, @fuels.map { |k, v| [k.humanize, v] }, { selected: @car.fuel_before_type_cast }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :category_id, "Categoría", class: common_label_classes %>
          <%= form.collection_select :category_id, @categories, :id, :name, { selected: @car.category_id || @default_category_id }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :origin_country_id, "País de origen", class: common_label_classes %>
          <%= form.collection_select :origin_country_id, @countries, :id, :name, { selected: @car.origin_country_id || @default_origin_country_id }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :vin, "Código VIN", class: common_label_classes %>
          <%= form.text_field :vin, class: common_input_classes %>
        </div>
      </div>
    </div>

    <!-- Motor -->
    <h3 class="<%= h3_classes %>">Motor</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4">
          <%= form.label :cubic_capacity, "CC", class: common_label_classes %>
          <%= form.number_field :cubic_capacity, step: 0.01, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :power, "Potencia (CV)", class: common_label_classes %>
          <%= form.number_field :power, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :transmission, "Transmisión", class: common_label_classes %>
          <%= form.select :transmission, @transmissions.map { |k, v| [k.humanize, v] }, { selected: @car.transmission_before_type_cast }, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :gearbox, "Caja de cambios", class: common_label_classes %>
          <%= form.select :gearbox, @gearboxes.map { |k, v| [k.humanize, v] }, { selected: @car.gearbox_before_type_cast }, class: common_input_classes %>
        </div>
      </div>
    </div>

    <!-- Consumos y Emisiones -->
    <h3 class="<%= h3_classes %>">Consumos y Emisiones</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4">
          <%= form.label :emission_sticker_id, "Etiqueta de Emisión", class: common_label_classes %>
          <%= form.collection_select :emission_sticker_id, @emission_stickers, :id, :name, {}, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :consumption_city, "Consumo en Ciudad (l/100km)", class: common_label_classes %>
          <%= form.number_field :consumption_city, step: 0.01, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :consumption_highway, "Consumo en Carretera (l/100km)", class: common_label_classes %>
          <%= form.number_field :consumption_highway, step: 0.01, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :consumption_combined, "Consumo Combinado (l/100km)", class: common_label_classes %>
          <%= form.number_field :consumption_combined, step: 0.01, class: common_input_classes %>
        </div>
      </div>
    </div>

    <!-- Exterior e Interior -->
    <h3 class="<%= h3_classes %>">Exterior e Interior</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4">
          <%= form.label :doors, "Número de puertas", class: common_label_classes %>
          <%= form.select :doors, options_for_select((1..5).map { |n| [n, n] }, selected: @car.doors || 5), {}, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :exterior_color, "Color Exterior", class: common_label_classes %>
          <%= form.text_field :exterior_color, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :seats, "Número de asientos", class: common_label_classes %>
          <%= form.select :seats, options_for_select((1..9).map { |n| [n, n] }, selected: @car.seats || 5), {}, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :interior_color, "Color del interior", class: common_label_classes %>
          <%= form.text_field :interior_color, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :interior_material, "Material del interior", class: common_label_classes %>
          <%= form.text_field :interior_material, class: common_input_classes %>
        </div>
      </div>
    </div>

    <!-- Visibilidad Web -->
    <h3 class="<%= h3_classes %>">Visibilidad Web</h3>
    <div class="<%= common_labels_div_classes %>">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="mb-4">
          <%= form.label :in_home_page, "Mostrar en Página Principal", class: common_label_classes %>
          <%= form.select :in_home_page, options_for_select([['Si', true], ['No', false]], @car.in_home_page), {}, class: common_input_classes %>
        </div>
        <div class="mb-4">
          <%= form.label :is_public, "Mostrar en la web de cliente?", class: common_label_classes %>
          <%= form.select :is_public, options_for_select([['Si', true], ['No', false]], @car.is_public), {}, class: common_input_classes %>
        </div>
      </div>
    </div>

    <!-- Imagenes -->
    <h3 class="<%= h3_classes %>">Imagenes</h3>
    <div class="<%= common_labels_div_classes %>">
      <% if @car.images.any? %>
        <div class="mb-4 mt-6">
          <label class="<%= common_label_classes %>">Imágenes existentes</label>
          <div class="grid grid-cols-2 md:grid-cols-3 gap-4">
            <% @car.images.each do |image| %>
              <div class="relative">
                <%= image_tag url_for(@car.medium_image(image)), alt: "Imagen del Coche", class: "w-full h-auto rounded" %>
                <!-- Botón para eliminar imagen -->
                <%= link_to 'Eliminar', remove_image_admin_car_path(@car, image.id), method: :delete, data: { confirm: '¿Estás seguro de eliminar esta imagen?' }, class: "absolute top-2 right-2 text-red-500 hover:text-red-700" %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="mb-4 mt-6 relative">
        <%= form.label :images, "Subir Imágenes del Coche", class: common_label_classes %>
        <div id="dropbox" class="w-full p-4 border-2 border-dashed border-gray-300 rounded-md text-center cursor-pointer" style="min-height: 10em; border-color: yellowgreen; position: relative;">
          <%= form.file_field :images, multiple: true, class: "absolute top-0 left-0 w-full h-full opacity-0 cursor-pointer", id: "image_input" %>
          <small class="text-gray-600">Arrastra y suelta archivos o haz clic para seleccionar múltiples imágenes.</small>
        </div>

        <div id="file-list" class="mt-4 text-gray-600"></div>
      </div>
    </div>

    <!-- Submit -->
    <div class="text-xl text-center mt-10 mb-10">
      <%= form.submit "Guardar Coche", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
<% end %>

app/views/admin/cars/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/cars/index.html.erb
<!-- app/views/admin/cars/index.html.erb -->
<div class="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-2xl font-bold">Listado de Coches</h1>
    <%= link_to 'Crear Nuevo Coche', new_admin_car_path, class: 'inline-flex items-center px-4 py-2 bg-indigo-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:ring focus:ring-indigo-200 active:bg-indigo-600 disabled:opacity-25 transition' %>
  </div>

  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Estado</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Precio</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Año</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Kilómetros</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Categoría</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Marca</th>
<!--              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">País de origen</th>-->
              <th scope="col" class="relative px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Acciones</th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            <% @cars.each do |car| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium text-gray-900"><%= car.name %></td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium text-gray-900"><%= car.status.humanize %></td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= number_to_currency(car.price, unit: "€") %></td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= car.year %></td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= car.kilometers %> km</td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= car.category.name if car.category %></td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= car.make.name if car.make %></td>
<!--                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%#= car.origin_country.name if car.origin_country %></td>-->
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium">
                  <div class="grid grid-cols-3 items-center">
                    <div class="flex justify-center"> <!-- Posición 2: Primer icono -->
                      <%= link_to '👁️', admin_car_path(car) %>
                    </div>
                    <div class="flex justify-center"> <!-- Posición 2: Primer icono -->
                      <%= link_to '✏️', edit_admin_car_path(car) %>
                    </div>
                    <div class="flex justify-center"> <!-- Posición 4: Segundo icono -->
                      <%= link_to '🗑️', admin_car_path(car), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar este coche?' } %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/cars/new.html.erb
<%= render partial: 'form' %>