config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :cars, only: [:index, :show], defaults: { format: :html }, path: "coches"
  # get "admin22", to: "admin#index"
  devise_scope :user do
    get "/admin22", to: "users/sessions#new"
  end

  get "admin", to: "admin#index"
  get "about_us", to: "static_pages#about_us"
  get "contacto", to: "contact_requests#new", as: "contact_request"
  post "contacto", to: "contact_requests#create"
  get "cookies_policy", to: "static_pages#cookies_policy"
  get "legal", to: "static_pages#legal"
  root "static_pages#home"

  namespace :admin do
    resources :cars do
      member do
        delete "remove_image/:image_id", to: "cars#remove_image", as: "remove_image"
      end
    end

    resources :contact_requests, only: [:index, :update, :destroy]
    resources :categories
    resources :category_types
  end

  # Default routes
  # To know the status of the app /up
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  belongs_to :car, optional: true
end

app/controllers/admin/contact_requests_controller.rb
module Admin
  class ContactRequestsController < AdminController
    def index
      @contact_requests = ContactRequest.all.order(created_at: :desc)
    end

    def update
      contact_request = ContactRequest.find(params[:id])
      if contact_request.update(contact_request_params)
        flash[:success] = "Solicitud actualizada correctamente"
      else
        flash[:error] = "Error al actualizar la solicitud"
      end

      redirect_to admin_contact_requests_path
    end

    def destroy
      contact_request = ContactRequest.find(params[:id])
      if contact_request.destroy
        flash[:success] = "Solicitud eliminada correctamente"
      else
        flash[:error] = "Error al eliminar la solicitud"
      end

      redirect_to admin_contact_requests_path
    end

    private

    def contact_request_params
      params.require(:contact_request).permit(:viewed)
    end
  end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  def new
    @contact_request = ContactRequest.new
    @contact_request.assign_attributes(car_id: params[:car_id]) if params[:car_id].present?
  end

  def create
    @contact_request = ContactRequest.new(contact_request_params)
    if @contact_request.save
      flash[:success] = "Solicitud enviada correctamente, nos pondremos en contacto contigo lo antes posible."
      redirect_to root_path
    else
      flash[:error] = "Error al enviar la solicitud."
      render :new
    end
  end

  private

  def contact_request_params
    params.require(:contact_request).permit(:name, :email, :phone, :subject, :message, :car_id)
  end
end

app/views/admin/contact_requests/_modal.html.erb
<div id="modal-<%= contact_request.id %>" class="fixed z-10 inset-0 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-center justify-center min-h-screen px-4 text-center sm:block sm:p-0">
    <div class="fixed inset-0 transition-opacity" aria-hidden="true">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>

<!--    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle" style="width: 40%; height: 80%;">-->
    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle w-4/5 lg:w-2/5">
      <!-- Modal Header -->
      <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
        <div class="sm:flex sm:items-start">
          <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
            <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">Detalles de Solicitud de Contacto</h3>
          </div>
        </div>
      </div>

      <!-- Modal Body with Scroll -->
      <div class="bg-gray-50 px-4 py-5 sm:px-6 overflow-auto" style="max-height: 80vh;">
        <p><strong>Nombre:</strong> <%= contact_request.name %></p>
        <p><strong>Email:</strong> <%= contact_request.email %></p>
        <p><strong>Teléfono:</strong> <%= contact_request.phone %></p>
        <p><strong>Asunto:</strong> <%= contact_request.subject %></p>
        <p><strong>Mensaje:</strong></p>
        <p class="whitespace-pre-line"><%= contact_request.message %></p>
        <div class="mt-4">
          <%= form_with(model: [:admin, contact_request], method: :patch, local: true) do |f| %>
            <%= f.label :viewed, "Marcar como revisado", class: "font-bold" %>
            <%= f.check_box :viewed %>
            <%= f.submit "Actualizar", class: "rounded-md border border-transparent shadow-sm px-2 py-1 bg-blue-600 text-sm font-medium text-white hover:bg-blue-700 ml-16 sm:w-auto" %>
          <% end %>
        </div>
      </div>

      <!-- Modal Footer -->
      <div class="bg-gray-100 px-4 py-3 sm:px-6 grid grid-cols-2 gap-4">
        <button type="button" class="close-modal w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 sm:mt-0 sm:w-auto sm:text-sm" data-modal-id="modal-1">
          Cerrar
        </button>
        <a href="mailto:<%= contact_request.email %>?subject=<%= CGI.escape(contact_request.subject) %>" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-green-600 text-base font-medium text-white hover:bg-green-700 sm:ml-3 sm:w-auto sm:text-sm">
          Enviar Email
        </a>
      </div>
    </div>
  </div>
</div>

app/views/admin/contact_requests/index.html.erb
<div class="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <h1 class="text-2xl font-bold mb-6">Listado de Solicitudes de Contacto</h1>

  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Teléfono</th>
<!--              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Asunto</th>-->
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Coche (ID)</th>
              <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Revisado?</th>
              <th scope="col" class="relative px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">Acciones</th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @contact_requests.each do |contact_request| %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium text-gray-900"><%= contact_request.name %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= contact_request.email %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= contact_request.phone %></td>
<!--                  <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%#= contact_request.subject %></td>-->
                  <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                    <% if contact_request.car_id.present? %>
                      <%= link_to contact_request.car&.name, admin_car_path(contact_request.car_id) %>
                    <% else %>
                      Sin coche asociado
                    <% end %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500"><%= contact_request.viewed ? '✅' : '❌' %></td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <div class="grid grid-cols-2 items-center">
                      <button class="flex justify-center py-2 px-4" data-modal-id="modal-<%= contact_request.id %>">👁</button>
                      <div class="flex justify-center">
                        <%= link_to '🗑️', admin_contact_request_path(contact_request), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta solicitud de contacto?' } %>
                      </div>
                    </div>
                  </td>
                </tr>

              <%= render partial: 'admin/contact_requests/modal', locals: { contact_request: contact_request } %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>