config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :cars, only: [:index, :show], defaults: { format: :html }, path: "coches"
  # get "admin22", to: "admin#index"
  devise_scope :user do
    get "/admin22", to: "users/sessions#new"
  end

  get "admin", to: "admin#index"
  get "about_us", to: "static_pages#about_us"
  get "contacto", to: "contact_requests#new", as: "contact_request"
  post "contacto", to: "contact_requests#create"
  get "cookies_policy", to: "static_pages#cookies_policy"
  get "legal", to: "static_pages#legal"
  root "static_pages#home"

  namespace :admin do
    resources :cars do
      member do
        delete "remove_image/:image_id", to: "cars#remove_image", as: "remove_image"
      end
    end

    resources :contact_requests, only: [:index, :update, :destroy]
    resources :categories
    resources :category_types
  end

  # Default routes
  # To know the status of the app /up
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :category
  belongs_to :make
  belongs_to :origin_country, class_name: "Country", foreign_key: "origin_country_id", optional: true

  has_many :contact_requests, dependent: :nullify

  has_many_attached :images

  validates :make, presence: true
  validate :image_count_within_limit
  validates :vin, uniqueness: true, allow_nil: true

  enum :status, { on_sale: 0, sold: 1, reserved: 2 }
  enum :condition, { km0: 0, used: 1 }
  enum :gearbox, { manual: 0, automatic: 1, semi_automatic: 2 }
  enum :transmission, { front_wheel_drive: 0, rear_wheel_drive: 1, four_wheel_drive: 2 }
  enum :fuel, { diesel: 0, petrol: 1, electric: 2, hybrid_petrol: 3, hybrid_diesel: 4, lpg: 5, cng: 6, other: 7 }

  before_save :set_vat_price_fields
  before_save :hide_car_if_sold

  def to_param
    "#{self.name.parameterize}-#{self.id}"
  end

  def image_urls
    self.images.map { |image| Rails.application.routes.url_helpers.url_for(image) }
  end

  def medium_image(image)
    image.variant(resize_to_fill: [300, 200], format: :jpg).processed
    # image.variant(resize_to_limit: [300, 200], format: :jpg).processed
  end

  def mediumbig_image(image)
    image.variant(resize_to_fill: [300, 480], format: :jpg).processed
    # image.variant(resize_to_limit: [300, 480], format: :jpg).processed
  end

  def big_image(image)
    image.variant(resize_to_fill: [1000, 1000], format: :jpg).processed
    # image.variant(resize_to_limit: [1000, 1000], format: :jpg).processed
  end

  def tiny_image(image)
    image.variant(resize_to_fill: [30, 30], format: :jpg).processed
    # image.variant(resize_to_limit: [30, 30], format: :jpg).processed
  end

  def get_full_name
    "#{self.make.name} #{self.name}"
  end

  private

  def image_count_within_limit
    if images.count < 1
      errors.add(:images, "must have at least one image")
    end
  end

  def set_vat_price_fields
    if self.new_record? || self.price_changed?
      tax = self.price * 1.21

      self.tax = tax.round(2)
      self.base_price = (self.price - tax).round(2)
    end
  end

  def hide_car_if_sold
    if self.status == "sold"
      self.in_home_page = false
      self.is_public = false
    end
  end
end

app/controllers/admin/cars_controller.rb
module Admin
  class CarsController < AdminController
    def index
      @cars = Car.all
    end

    def show
      @car = Car.find(get_car_id)
      render template: "cars/show"
    end

    def edit
      all_select_options
      default_form_field_values

      @car = Car.find(get_car_id)
    end

    def new
      all_select_options
      default_form_field_values
    end

    def update
      @car = Car.find(get_car_id)

      if car_params[:images].present?
        @car.images.attach(car_params[:images])
      end

      if @car.update(car_params.except(:images))
        message = "El coche se actualizó correctamente."
        message += " Se ha ocultado de la página de inicio y de la web ya que el coche está vendido." if @car.sold?
        redirect_to admin_car_path(@car), notice: message
      else
        render "edit"
      end
    end

    def create
      @car = Car.new(car_params)
      if @car.save
        flash[:success] = "Coche creado correctamente."
        redirect_to admin_car_path(@car)
      else
        flash[:error] = "Error al crear el coche."
        redirect_to new_admin_car_path(car_params)
      end
    end

    def destroy
      @car = Car.find(get_car_id)
      @car.destroy

      redirect_to admin_cars_path
    end

    def remove_image
      @car = Car.find(get_car_id)
      image = @car.images.find(params[:image_id])
      image.purge  # Elimina la imagen

      redirect_to edit_admin_car_path(@car), notice: "Imagen eliminada con éxito."
    end

    private

    def car_params
      params.require(:car).permit(
        :category_id, :make_id, :emission_sticker_id, :condition, :first_registration, :transmission, :gearbox, :fuel, :model,
        :cubic_capacity, :power, :previous_owners, :origin_country_id,:model_description, :name, :price, :year, :kilometers,
        :description, :in_home_page, :is_public, :status, :next_inspection, :exterior_color, :manufacturer_color_name, :doors, :seats,
        :interior_color, :interior_material, :vin, :consumption_city, :consumption_suburban, :consumption_highway,
        :consumption_combined, :base_price, :tax, :total_price, images: []
      ).tap do |p|
        p[:condition] = p[:condition].to_i if p[:condition].present?
        p[:gearbox] = p[:gearbox].to_i if p[:gearbox].present?
        p[:transmission] = p[:transmission].to_i if p[:transmission].present?
        p[:fuel] = p[:fuel].to_i if p[:fuel].present?
        p[:status] = p[:status].to_i if p[:status].present?
        p[:vin] = p[:vin].presence
      end
    end

    def all_select_options
      @car = Car.new
      @categories = Category.all.order(:name)
      @makes = Make.all.order(:name)
      @emission_stickers = EmissionSticker.all.order(:name)
      @countries = Country.all.order(:name)

      fuels_desired_order = %w[petrol diesel electric hybrid_petrol hybrid_diesel other]
      @fuels = Car.fuels.sort_by { |key, _| fuels_desired_order.index(key.to_s) || fuels_desired_order.size }
      @conditions = Car.conditions.sort_by { |key, _| key.to_s }.reverse.to_h
      @transmissions = Car.transmissions.sort_by { |key, _| key.to_s }.to_h
      @gearboxes = Car.gearboxes.sort_by { |key, _| key.to_s }.to_h
      @statuses = Car.statuses.sort_by { |key, _| key.to_s }.to_h
    end

    def default_form_field_values
      @default_make_id = Make.find_by(name: "Porsche").id
      @default_origin_country_id = Country.find_by(name: "Spain").id
      @default_category_id = Category.find_by(name: "SUV").id
    end
  end
end
# {"on_sale"=>0, "reserved"=>2, "sold"=>1}

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.where.not(status: :sold)
  end

  def show
    @car = Car.find(get_car_id)
  end
end

app/views/cars/index.html.erb
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
  <h1 class="text-3xl font-bold text-gray-900 mb-8 text-center">Nuestros Coches</h1>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-8">
    <% @cars.each do |car| %>
      <%= render partial: 'components/car_card', locals: { car: car } %>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<!-- app/views/cars/show.html.erb -->
<% if in_admin_controller? %>
  <div class="mt-8 flex justify-between">
    <%= link_to 'Volver al listado anterior', 'javascript:history.back()', class: 'inline-block px-6 py-3 bg-gray-600 text-white text-lg font-medium rounded-md hover:bg-gray-700' %>
    <%= link_to 'Editar este coche', edit_admin_car_path(@car), class: 'inline-block px-6 py-3 bg-indigo-600 text-white text-lg font-medium rounded-md hover:bg-indigo-700' %>
  </div>
<% end %>

<div class="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <h1 class="text-center text-3xl font-bold mb-8"><%= @car.get_full_name %></h1>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
    <%= render partial: "components/car_swiper", locals: { car: @car } %>
    <div>
      <div class="bg-white p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold mb-4">Detalles del coche</h2>
        <dl class="space-y-2">
          <div class="flex justify-between">
            <dt class="font-medium text-gray-500">Precio</dt>
            <dd class="text-lg text-gray-900"><%= number_to_currency(@car.price, unit: "€") %></dd>
          </div>
          <div class="flex justify-between">
            <dt class="font-medium text-gray-500">Año</dt>
            <dd class="text-lg text-gray-900"><%= @car.year %></dd>
          </div>
          <div class="flex justify-between">
            <dt class="font-medium text-gray-500">Kilómetros</dt>
            <dd class="text-lg text-gray-900"><%= @car.kilometers %> km</dd>
          </div>
          <div class="flex justify-between">
            <dt class="font-medium text-gray-500">Marca</dt>
            <dd class="text-lg text-gray-900"><%= @car.make.name if @car.make %></dd>
          </div>
          <div class="flex justify-between">
            <dt class="font-medium text-gray-500">Categoría</dt>
            <dd class="text-lg text-gray-900"><%= @car.category.name if @car.category %></dd>
          </div>
<!--          <div class="flex justify-between">-->
<!--            <dt class="font-medium text-gray-500">País de origen</dt>-->
<!--            <dd class="text-lg text-gray-900"><%#= @car.origin_country.name if @car.origin_country %></dd>-->
<!--          </div>-->
        </dl>
      </div>

      <div class="mt-8">
        <% if in_admin_controller? %>
<!--          <a href="javascript:void(0);" class="inline-block w-full text-center px-6 py-3 bg-gray-400 text-white text-lg font-medium rounded-md cursor-not-allowed" aria-disabled="true">-->
<!--            Contactar sobre este coche (Deshabilitado en Admin)-->
<!--          </a>-->
        <% else %>
          <%#= link_to 'Contactar sobre este coche', contacto_path(car_id: @car.id), class: 'inline-block w-full text-center px-6 py-3 bg-indigo-600 text-white text-lg font-medium rounded-md hover:bg-indigo-700' %>
          <%= link_to 'Contactar sobre este coche', "https://wa.me/#{Rails.application.credentials.dig(:whatsapp, :phone_number)}?text=Estoy%20interesado%20en%20el%20coche%20#{@car.name}%20-%20#{car_url(@car)}%0A", class: 'inline-block w-full text-center px-6 py-3 bg-indigo-600 text-white text-lg font-medium rounded-md hover:bg-indigo-700', target: '_blank', rel: 'noopener' %>
      <% end %>
      </div>
    </div>
  </div>

  <!-- Descripción larga del coche -->
  <div class="mt-12 bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-2xl font-semibold mb-4">Descripción</h2>
    <p class="text-gray-700 leading-relaxed"><%= @car.model_description %></p>
  </div>
</div>